<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <script>
        // 原Promise对象的状态将跟新对象保持一致
        // Promise.resolve().then(() => {
        //     console.log('ok1')
        //     return new Promise(() => { })  // 返回“pending”状态的Promise对象
        // }).then(() => {
        //     // 后续的函数不会被调用
        //     console.log('ok2')
        // }).catch(err => {
        //     console.log('err->', err)
        // })


        // Promise.race方法：
        // let p1 = new Promise((resolve, reject) => {
        //     resolve('ok1')
        // })

        // let p2 = new Promise((resolve, reject) => {
        //     setTimeout(() => { resolve('ok2') }, 10)
        // })

        // Promise.race([p2, p1]).then((result) => {
        //     console.log(result) //ok1
        // }).catch((error) => {
        //     console.log(error)
        // })


        // 3、当Promise链中抛出一个错误时，错误信息沿着链路向后传递，直至被捕获。
        Promise.resolve().then(() => {
            console.log('ok1')
            throw 'throw error1'
        }).then(() => {
            console.log('ok2')
        }, err => {
            // 捕获错误
            console.log('err->', err)
        }).then(() => {
            // 该函数将被调用
            console.log('ok3')
            throw 'throw error3'
        }).then(() => {
            // 错误捕获前的函数不会被调用
            console.log('ok4')
        }).catch(err => {
            console.log('err->', err)
        })
    </script>
</body>

</html>